#!/bin/bash

echo 'lines	words	bytes	file'
echo '-----	-----	-----	----'

wc flask_metar.py jinja2_helpers.py babel.cfg static/css/my.css static/js/my.js templates/* messages.pot \
	| sort -gr \
	| sed -r 's/ +/\t/g' \
	| sed -r 's/^\t/ /g'
